name: Deploy to Stage server

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js and npm
        uses: actions/setup-node@v4
        with:
          node-version: 18 # Adjust if needed
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Run Remote/Artisan Commands
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.VPS_HOST_STAGE }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo rm -rf /var/www/html/exampazz-admin-frontend
            sudo mkdir /var/www/html/exampazz-admin-frontend
            sudo chown -R $USER:www-data /var/www/html/exampazz-admin-frontend
              
      - name: Synchronize Files To Server
        uses: easingthemes/ssh-deploy@v5.1.0
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SOURCE: "dist/"
          REMOTE_HOST: ${{ secrets.VPS_HOST_STAGE }}
          REMOTE_USER: ${{ secrets.VPS_USER }}
          TARGET: "/var/www/html/exampazz-admin-frontend"
          EXCLUDE: "/dist/, /node_modules/"

      - name: Run Remote/Artisan Commands
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.VPS_HOST_STAGE }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo nginx -s reload
            
